{% set name = "bw2parameters" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37d2e242334c7c688444296048257616e4b03580929c18faf6c2286e122b2b79

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - asteval
    - astunparse
    - numpy
    - pint
    - python >={{ python_min }}
    - stats_arrays

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/brightway2-parameters
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Library for storing, validating, and calculating with parameters
  description: |
      Designed to work with the Brightway2 life cycle assessment framework, but is
      generic enough to work in other use cases.
  dev_url: https://github.com/brightway-lca/brightway2-parameters

extra:
  recipe-maintainers:
    - cmutel
